export const taroTonData = [
    {
        url: 'https://www.postype.com/@00010v2/post/22146661',
        title: '레몬스퀴지 2',
        author: '롵',
        date: '2026. 4. 28.',
        is_adult: 'True',
        views: 440,
        price: 0,
        likes: 31,
        category: 'novel',
        summary: '여기 앉으면 되나요...? 네. 앉으시면 됩니다. 우왕... 이런 스튜디오 처음 와 봐요. 키즈 모델 일 하셨다고 들었어요. 네, 근데 너무 어렸고... 기억도 잘 안 나서 저는 ...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732083',
        title: 'Home, Sweet Home 1',
        author: '에스티',
        date: '2025. 10. 29.',
        is_adult: 'False',
        views: 592,
        price: 0,
        likes: 18,
        category: 'novel',
        summary: '※ 톤른(숕톤, 돌톤, 숑톤, 넨톤)으로 모든 커플링이 한번씩 번갈아가며 메인이 됩니다. ※ 완결 후 유료 전환됩니다. 1화(이찬영 편) 쇼타로, 송은석, 정성찬, 박원빈X이찬영 ...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/18249027',
        title: 'Brothers(下)',
        author: '에스티',
        date: '2024. 12. 27.',
        is_adult: 'False',
        views: 410,
        price: 100,
        likes: 16,
        category: 'novel',
        summary: '톤른(숕톤, 숑톤, 돌톤, 넨톤) 텍스트 5,776 자 공백 제외'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732105',
        title: 'Home, Sweet Home 3',
        author: '에스티',
        date: '2025. 11. 12.',
        is_adult: 'False',
        views: 261,
        price: 0,
        likes: 15,
        category: 'novel',
        summary: '3화(정성찬 편) 정성찬X이찬영 “오늘 왜 또 학교 안 갔어?” “이번 주말에 대회가 있어서 밤새 연습하느라 늦잠을 자 버렸어.” “출석일수도 간당간당 할 텐데 시험까지 안 보면 ...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/18249018',
        title: 'Brothers(上)',
        author: '에스티',
        date: '2024. 12. 26.',
        is_adult: 'False',
        views: 491,
        price: 100,
        likes: 15,
        category: 'novel',
        summary: '톤른(숕톤, 돌톤, 넨톤) 텍스트 5,792 자 공백 제외'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732145',
        title: 'Home, Sweet Home 7',
        author: '에스티',
        date: '2025. 12. 10.',
        is_adult: 'False',
        views: 183,
        price: 0,
        likes: 13,
        category: 'novel',
        summary: '7화(송은석 편) 송은석X이찬영 그는 어느 날 갑자기 사라져 버렸다. 이유를 생각해 보자면 한 가지밖에는 없었다. 며칠 전 어두운 동네 골목길에서 장난스레 키스를 하던 그들이 은석...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732183',
        title: 'Home, Sweet Home 10(完)',
        author: '에스티',
        date: '2025. 12. 31.',
        is_adult: 'False',
        views: 0,
        price: 0,
        likes: 12,
        category: 'novel',
        summary: '10화(이찬영 편) 쇼타로, 송은석, 정성찬, 박원빈X이찬영 -작가님! 드디어 ‘선배, 거긴 안 돼♡’가 조회수 1위에 올랐어요! “하하, 그거 참 잘됐네요.” 은석은 마감도 했는...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732114',
        title: 'Home, Sweet Home 4',
        author: '에스티',
        date: '2025. 11. 19.',
        is_adult: 'False',
        views: 207,
        price: 0,
        likes: 12,
        category: 'novel',
        summary: '4화(쇼타로 편) 쇼타로X이찬영 쇼타로의 곁에는 언제나 누군가가 있었다. 남자든, 여자든 상관없이 가리지 않고 한 달에 한두 번씩 바뀌어 있었다. 그는 그런 부류의 사람이라고 생각...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732097',
        title: 'Home, Sweet Home 2',
        author: '에스티',
        date: '2025. 11. 5.',
        is_adult: 'False',
        views: 328,
        price: 0,
        likes: 11,
        category: 'novel',
        summary: '2화(송은석 편) 송은석X이찬영 찬영은 유난히 작은 아이였다. 키가 지금처럼 크게 된 건 찬영이 고등학교에 들어가서였고, 중학생 시절 그는 키도 작고 빼빼마른 소년이었다. 14살의...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732139',
        title: 'Home, Sweet Home 6',
        author: '에스티',
        date: '2025. 12. 3.',
        is_adult: 'False',
        views: 257,
        price: 0,
        likes: 9,
        category: 'novel',
        summary: '6화(정성찬 편) 정성찬X이찬영 “성찬이 형, 진짜 왜 그래?” 눈꼬리를 타고 눈물이 주르륵 흘러내렸다. 씨이. 재빨리 손등으로 눈물을 훔치며 입술을 깨물어 보았지만, 바르르 떨리...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732126',
        title: 'Home, Sweet Home 5',
        author: '에스티',
        date: '2025. 11. 26.',
        is_adult: 'False',
        views: 211,
        price: 0,
        likes: 9,
        category: 'novel',
        summary: '5화(박원빈 편) 박원빈X이찬영 금사빠. 금세 사랑에 빠지는 사람. 박원빈에게 붙여진 별명이었다. 한 달도 채 되지 않아 이별을 고하는 원빈이 한결같이 듣는 말이 있었다. “넌 쉽...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732173',
        title: 'Home, Sweet Home 9',
        author: '에스티',
        date: '2025. 12. 24.',
        is_adult: 'False',
        views: 144,
        price: 0,
        likes: 7,
        category: 'novel',
        summary: '9화(박원빈 편) 박원빈X이찬영 이찬영은 금세 취해버렸다. 술이 약한 편은 아니었지만 그날따라 앞뒤 가리지 않고 마구 마셔대던 탓이 컸다. 테이블 위에 코를 박고 정신을 잃어버린 ...'
    },
    {
        url: 'https://www.postype.com/@slowly-st/post/19732160',
        title: 'Home, Sweet Home 8',
        author: '에스티',
        date: '2025. 12. 17.',
        is_adult: 'False',
        views: 157,
        price: 0,
        likes: 7,
        category: 'novel',
        summary: '8화(쇼타로 편) 쇼타로X이찬영 “너 때문에 심장이 뛴다는 건 거짓말이야. 사실 난 남들보다 심장이 빠르게 뛰는 편이거든.” 자, 지금도 그렇지? 이렇게 말하며 찬영의 손바닥을 쇼...'
    },
]