export const heeDolData = [
    {
        "url": "https://www.postype.com/@riizeontop/post/16551341",
        "title": "원테이크",
        "author": "𝝑𝝔",
        "date": "2024. 5. 23.",
        "is_adult": "True",
        views: 5200,
        price: 1500,
        likes: 133,
        "category": "novel",
        "summary": "오백..? 성찬은 은석이 말한 금액에 혹했다. 하루 촬영에 오백이라니. 알바치고 상당히 괜찮은 금액이라 절대 안한다던 마음이 순식간에 가능 쪽으로 돌아섰다. 애초에 송은석 입에..."
    },
    {
        "url": "https://www.postype.com/@yla0233/post/16713097",
        "title": "연습실",
        "author": "겸",
        "date": "2024. 4. 30.",
        "is_adult": "True",
        views: 5500,
        price: 1000,
        likes: 114,
        "category": "novel",
        "summary": "개오바같지만 숑또석 들박을 봐야만 하겠다면...? 연습실에 남아 추가 연습하던 세 사람. 마지막 연습 끝내고 이소희랑 정성찬 연습실 바닥에 드러누움. 물마시러 가는 것도 힘들다며 ..."
    },
    {
        "url": "https://www.postype.com/@stone69/post/19933083",
        "title": "돌른 석른 썰 백업1",
        "author": "ㅅㄸㅅㄸ",
        "date": "2025. 7. 15.",
        "is_adult": "True",
        views: 3200,
        price: 0,
        likes: 90,
        "category": "novel",
        "summary": "만약 성향자라면? 에 대한 썰조각들 마조공 넨석 약간 스폰서 넨 아무 성향도 없는 아이돌 석 마조공이긴 한데 마조보단 마조돔에 가까워서 석이 목조르는 행위로 자신에게 복종하고 어쩔..."
    },
    {
        "url": "https://www.postype.com/@stone69/post/18279372",
        "title": "먹게? 먹고싶어?",
        "author": "ㅅㄸㅅㄸ",
        "date": "2024. 12. 22.",
        "is_adult": "True",
        views: 3000,
        price: 0,
        likes: 75,
        "category": "novel",
        "summary": "쿠당탕- 송은석을 부축한 채 겨우 현관문을 지나 침대에 쓰러지듯 송은석을 던졌다. 가쁜 숨을 몰아쉬며 냉장고로 가 생수를 벌컥 들이켰다. 하, 힘들어.. 입고있던 후드를 벗어 얼굴..."
    },
    {
        "url": "https://www.postype.com/@sn1054/post/5059803",
        "title": "[명우유진] 또석이",
        "author": "객성",
        "date": "2019. 11. 3.",
        "is_adult": "False",
        views: 873,
        price: 0,
        likes: 64,
        "category": "novel",
        "summary": "- 방은 구했냐? 군복학생의 외로운 처지를 타파해보고자 돌아온 동아리방은 잡동사니 창고로 전락한 지 오래다. 어디서 나타났는지도 알 수 없는 밥상을 펴놓고 퍼즐 맞추기에 열중하..."
    },
    {
        "url": "https://www.postype.com/@tallsizeplz/post/17818685",
        "title": "짝사랑 미러전",
        "author": "자허블",
        "date": "2024. 10. 15.",
        "is_adult": "False",
        views: 749,
        price: 700,
        likes: 60,
        "category": "novel",
        "summary": "뭐냐. 동아리실 쇼파에 거의 눕듯이 앉아 쿠키런을 조지는데 문 열리는 소리가 났다. 금세 옆자리가 푹 꺼지더니 익숙한 향이 끼친다 싶더니 뭐냐. 대뜸 날아오는 무미건조한 말에 ..."
    },
    {
        "url": "https://www.postype.com/@0103193/post/18184029",
        "title": "안정 경계",
        "author": "mall",
        "date": "2025. 1. 21.",
        "is_adult": "False",
        views: 740,
        price: 0,
        likes: 48,
        "category": "novel",
        "summary": "형, 친구는 어떻게 사귀어? 이제 초등학교 2학년 올라가는 사촌 동생의 질문에 이소희는 고민한다. 글쎄? 그냥 말 걸면 되지 않나? 이제 대학교 2학년 올라가는 이소희는 이런 질문..."
    },
    {
        "url": "https://www.postype.com/@0103193/post/18184046",
        "title": "애정 경계",
        "author": "mall",
        "date": "2025. 5. 8.",
        "is_adult": "False",
        views: 470,
        price: 0,
        likes: 44,
        "category": "novel",
        "summary": "mall 2025. 1. 21. · 𖠌 안정 경계 또석 형, 친구는 어떻게 사귀어? 이제 초등학교 2학년 올라가는 사촌 동생의 질문에 이소희는 고민한다. 글쎄? 그냥 말 걸면 되지..."
    },
    {
        "url": "https://www.postype.com/@fnsosb/post/17206856",
        "title": "또석",
        "author": ".",
        "date": "2024. 7. 21.",
        "is_adult": "True",
        views: 2900,
        price: 500,
        likes: 40,
        "category": "novel",
        "summary": "비윤리적인 소재 多 하트신음, 실금, 피스트퍽, 결장, 모브 이웃집 살고있다는 설정으로 어릴때부터 알고지냈으면 좋겠네... 초딩과 싸울때도 진심을 다하는 송군 소희 앞에 가는거 보..."
    },
    {
        "url": "https://www.postype.com/@affirmationof01/post/18467066",
        "title": "프레이 (1)",
        "author": "af-",
        "date": "2025. 1. 27.",
        "is_adult": "False",
        views: 633,
        price: 0,
        likes: 25,
        "category": "novel",
        "summary": "*글에 나오는 모든 지명과 이름, 사건은 허구입니다. 1. 흑백논리 열 일곱이란, 격변의 시기이다. 4번의 계절 이후에는 더이상 어리다 치부할 수 없는 시기가 성큼 다가오고, 권태..."
    },
    {
        "url": "https://www.postype.com/@fnsosb/post/17207019",
        "title": "숑넨 또석 히넨 숑석",
        "author": ".",
        "date": "2024. 7. 21.",
        "is_adult": "True",
        views: 3000,
        price: 800,
        likes: 24,
        "category": "novel",
        "summary": "비윤리적인 소재 多 가정폭력, 공의 신체적 정신적 폭력, 아헤가오, 가스라이팅, 3p, 스와핑, 모브 등 나 쇼타오니 또석이랑 오니쇼타 숑넨 만나게하고시푼데 정신병인걸까 아 꼴리는..."
    },
    {
        "url": "https://www.postype.com/@stone69/post/22728238",
        "title": "또석 20살",
        "author": "ㅅㄸㅅㄸ",
        "date": "2026. 7. 21.",
        "is_adult": "False",
        views: 163,
        price: 0,
        likes: 21,
        "category": "novel",
        "summary": "소희가 그렇게 힘이 센 줄 몰랐다. 평소에는 무거운 것을 대신 들거나 문을 먼저 잡아주는 식으로 자신이 남자라는 사실을 굳이 증명하려 들지만 은석이 보기에는 자신보다 작은, 어린 ..."
    },
    {
        "url": "https://www.postype.com/@fnsosb/post/17207279",
        "title": "또석",
        "author": ".",
        "date": "2024. 7. 21.",
        "is_adult": "True",
        views: 2200,
        price: 400,
        likes: 20,
        "category": "novel",
        "summary": "비윤리적인 소재 多 걍 피스트퍽만 합니다 하트신음 있음 텍스트 1,081 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@ddongeulover/post/21268702",
        "title": "종말 직전",
        "author": "강",
        "date": "2026. 7. 5.",
        "is_adult": "False",
        views: 377,
        price: 0,
        likes: 18,
        "category": "novel",
        "summary": "*세 사람 전부 리버시블이니 원하는 방식으로 읽으시면 됩니다. 은석과 소희는 동족이다. 내일 마침내 인류의 종말이 다가와도 소희와 은석은 때가 됐구나. 즐거웠다 그치. 하고 집에 ..."
    },
    {
        "url": "https://www.postype.com/@instfor252/post/21236687",
        "title": "환승연애 나갈래?",
        "author": "inst",
        "date": "2025. 12. 31.",
        "is_adult": "False",
        views: 299,
        price: 200,
        likes: 17,
        "category": "novel",
        "summary": "그렇게 나가게 된 환승연애. 미팅이 어찌저찌 끝나고 시간이 지나 첫 입소 날, 소희가 가장 먼저 숙소에 도착함. “ 와- 되게 넓다.. 엇, 이거 읽어야 하는 건가요? “ 숙소에 ..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18775709",
        "title": "돌 쟁탈전 上",
        "author": "얼음땡",
        "date": "2025. 5. 31.",
        "is_adult": "False",
        views: 836,
        price: 0,
        likes: 17,
        "category": "novel",
        "summary": "본 이야기의 내용은 실제와 무관합니다 캐붕 주의 참고 은석 <쇼타로> 《성찬》 - 원빈 {소희} [앤톤] @멤버 전체 송은석, 내 나이 24살. 지금 내 인생 최대의 시련이 왔..."
    },
    {
        "url": "https://www.postype.com/@showertowel/post/19740239",
        "title": "뱀파이어를 조심해!",
        "author": "샴푸",
        "date": "2025. 7. 15.",
        "is_adult": "False",
        views: 247,
        price: 0,
        likes: 13,
        "category": "novel",
        "summary": "무더운 여름이다. 소희는 여름방학을 맞아 평소에 얼굴을 보기 힘들었던 시골에 있던 할머니댁으로 내려왔다. 도시의 여름과 시골의 여름은 많이 달랐다. 도시는 사람들이 북적거려 답답하..."
    },
    {
        "url": "https://www.postype.com/@iamsrry/post/17719881",
        "title": "독잇뱀 돌과",
        "author": "abnormal_tnt",
        "date": "2024. 9. 30.",
        "is_adult": "False",
        views: 242,
        price: 0,
        likes: 12,
        "category": "novel",
        "summary": "계절은 여름에서 가을로 바뀌었고, 햇빛은 곧바로 내리 쬐었다. 아침 공기는 얇게 저민 얼음 조각처럼 따갑고 누군가의 스마트 폰에서는 독감을 조심하라는 공익 광고가 흘러나온다. 기상..."
    },
    {
        "url": "https://www.postype.com/@affirmationof01/post/21011280",
        "title": "프레이 (4)",
        "author": "af-",
        "date": "2026. 4. 11.",
        "is_adult": "False",
        views: 119,
        price: 0,
        likes: 10,
        "category": "novel",
        "summary": "*글에 나오는 모든 지명과 이름, 사건은 허구입니다. 4. 발발 잡힐 듯 잡히지 않는 그 위태로움이 좋았던 것 같다. 나는 네가 위태로운 게 좋아. 이실장 걔가 그러더라. 뭘 선택..."
    },
    {
        "url": "https://www.postype.com/@yallario/post/22650643",
        "title": "숑또석 낙인",
        "author": "호잇",
        "date": "2026. 7. 7.",
        "is_adult": "False",
        views: 134,
        price: 0,
        likes: 9,
        "category": "novel",
        "summary": "나에게 이소희란 처음부터 그런 존재였다. 느닷없는 아버지의 재혼으로 생긴 이미 다 커버린 동생. 고작 '가족'이라는 두 글자로는 도저히 끈끈해질 수 없는 그런 어긋난 존재. 그럼에..."
    },
    {
        "url": "https://www.postype.com/@affirmationof01/post/18610374",
        "title": "프레이 (2)",
        "author": "af-",
        "date": "2025. 2. 4.",
        "is_adult": "False",
        views: 272,
        price: 0,
        likes: 9,
        "category": "novel",
        "summary": "*글에 나오는 모든 지명과 이름, 사건은 허구입니다. 2. 주홍글씨 그를 좋아하게 된 순간으로 거슬러 올라가 보자. 신호 저 건너편에서 우뚝 서 있는 모양새에 저절로 눈이 간 것 ..."
    },
    {
        "url": "https://www.postype.com/@riize-briize0904-2023/post/19963497",
        "title": "또석",
        "author": "B R T",
        "date": "2025. 7. 19.",
        "is_adult": "False",
        views: 304,
        price: 0,
        likes: 6,
        "category": "novel",
        "summary": "-형, 키스해요. -나 립밤 발랐어.- -어쩌라고요, 입술 대요~ -..안된다고 말 했잖아. 송은석의 뺨을 가볍게 감싸고 평소처럼 익숙하게 키스하는 이소희, 송은석의..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/19022240",
        "title": "조각을 모아드립니다",
        "author": "얼음땡",
        "date": "2025. 6. 8.",
        "is_adult": "False",
        views: 637,
        price: 0,
        likes: 6,
        "category": "novel",
        "summary": "(2025년 3월 24일 추가) 텍스트 4,816 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@affirmationof01/post/18931538",
        "title": "프레이 (3)",
        "author": "af-",
        "date": "2025. 11. 20.",
        "is_adult": "False",
        views: 268,
        price: 0,
        likes: 6,
        "category": "novel",
        "summary": "3. 잘못된 신념은 집착과 다를 바 없다. 열 일곱이란, 격동의 시기이다. 둘이 처음 마주한 날은 이 시기를 암시라도 한 듯 엉망이었는데, 원빈은 머리칼이 잡아 뜯겨진 채 흠씬 얻..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18822683",
        "title": "돌 쟁탈전 中",
        "author": "얼음땡",
        "date": "2025. 5. 31.",
        "is_adult": "False",
        views: 336,
        price: 0,
        likes: 6,
        "category": "novel",
        "summary": "죽음, 자살 소재 주의 ??? : 은석이 형... 일어나 누구지? 익숙한 목소리다 ??? : 형, 일어나 내가 잊고 살아가던 소중한 사람, 동생의 목소리다 왜? 이제 왔어? 내가..."
    },
    {
        "url": "https://www.postype.com/@dlrjwjrj-39/post/22914775",
        "title": "더위 먹은 김에 직진!",
        "author": "효",
        "date": "2026. 8. 14.",
        "is_adult": "False",
        views: 57,
        price: 0,
        likes: 5,
        "category": "novel",
        "summary": "소희야. 네. 나 너 좋아한다. 에? 이번 여름이 진짜 미친 듯이 덥긴 더웠다. 가난한 대학생으로 신분 하락한 지 오래라 여름 보양식도 못 먹었더니 더위를 단단히 먹..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/20065265",
        "title": "썰 대방출",
        "author": "얼음땡",
        "date": "2025. 7. 30.",
        "is_adult": "False",
        views: 662,
        price: 0,
        likes: 4,
        "category": "novel",
        "summary": "이걸 이어서 쓸지 안 쓸지 몰라서 올려봅니다 반응 좋은 글은 더 써올게요 그럼 재밌게 읽어주세요 텍스트 3,040 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18913976",
        "title": "돌 쟁탈전…? 下",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 358,
        price: 0,
        likes: 4,
        "category": "novel",
        "summary": "텍스트 4,409 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18862448",
        "title": "돌 쟁탈전…? 上",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 421,
        price: 0,
        likes: 3,
        "category": "novel",
        "summary": "텍스트 4,657 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18845427",
        "title": "돌 쟁탈전 下",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 253,
        price: 0,
        likes: 3,
        "category": "novel",
        "summary": "편지도 다 썼겠다. 이제 자야지... 내일 일찍 나가야 하니깐. 행복할 기회를 안 주네. 내 몸이 밉다. 이젠 행복해질 수 있을 거 같았는데 또... 지난번엔 동생이 죽더니 이번엔..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18833723",
        "title": "돌 쟁탈전 中中",
        "author": "얼음땡",
        "date": "2025. 5. 31.",
        "is_adult": "False",
        views: 294,
        price: 0,
        likes: 2,
        "category": "novel",
        "summary": "<자~ 은석이의 퇴원을 축하하며!> 퇴원 하는 거까지 축하받다니;; 희한하네 <오늘은 우리 술 못 마신다. 은석이가 술 금지 당했거든ㅠ> 진짜? <엉, 의사 선생님이 한 주 동..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18891223",
        "title": "돌 쟁탈전…? 中",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 226,
        price: 0,
        likes: 1,
        "category": "novel",
        "summary": "텍스트 4,562 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@dropchodori/post/5892610",
        "title": "또석",
        "author": "ㄹ",
        "date": "2020. 2. 19.",
        "is_adult": "False",
        views: 49,
        price: 0,
        likes: 1,
        "category": "webtoon",
        "summary": "(자꾸 늘어나는데 얘로 끝낼거임..진짜) 평행세계의 루벨이랑 몰다 사귄..다.... (이때까지만 해도 모브..였음.....)"
    },
    {
        "url": "https://www.postype.com/@dropchodori/post/5463299",
        "title": "디아니아",
        "author": "ㄹ",
        "date": "2020. 1. 2.",
        "is_adult": "False",
        views: 12,
        price: 0,
        likes: 1,
        "category": "webtoon",
        "summary": "버닝장르라서 에유 100일겸 크리스마스축전"
    },
    {
        "url": "https://www.postype.com/@dropchodori/post/4756474",
        "title": "또석에유",
        "author": "ㄹ",
        "date": "2019. 9. 20.",
        "is_adult": "False",
        views: 14,
        price: 0,
        likes: 1,
        "category": "webtoon",
        "summary": ""
    }
]