export const shoDolData = [
    {
        "url": "https://www.postype.com/@sweetpoison/post/18660512",
        "title": "의외의 진심",
        "author": "독",
        "date": "2025. 2. 28.",
        "is_adult": "True",
        views: 3600,
        price: 0,
        likes: 182,
        "category": "novel",
        "summary": "쇼타로는 눈치가 빠른 편이었다. 그리고 외로움을 유리하게 즐기는 법을 알았다. 이토록 전혀 다른 명제의 상관관계는 뭘까. 조금 톤이 높은 한국어를 동그랗게 구사하며, 잔뜩 눈을 접..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/17898117",
        "title": "일방통행",
        "author": "독",
        "date": "2024. 10. 31.",
        "is_adult": "True",
        views: 3000,
        price: 0,
        likes: 162,
        "category": "novel",
        "summary": "텍스트 10,054 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/18977839",
        "title": "미학에 대하여",
        "author": "독",
        "date": "2025. 3. 19.",
        "is_adult": "True",
        views: 3200,
        price: 0,
        likes: 143,
        "category": "novel",
        "summary": "* 의외의 진심 에 이어집니다. 안 보셔도 상관은 없어요. 송은석은 쇼타로가 좋아서 죽을 것 같았다. 진짜 가끔은 숨도 안 쉬어질 정도였다. - 아, 읏... 여러가지 이유로. 그..."
    },
    {
        "url": "https://www.postype.com/@dollectionbook/post/16564633",
        "title": "숕석 브컨",
        "author": "박흰돌",
        "date": "2024. 4. 3.",
        "is_adult": "True",
        views: 7600,
        price: 100,
        likes: 132,
        "category": "novel",
        "summary": "이상한 자컨 땜에 이상성욕 발현해서 이땅거 그임 암튼 나에 책임이 아닌것 이 둘.. 서로에게 맞춰주고 잇다고 생각하며 브컨을 할거갓흠 얼굴은 잘생겻는데 헨따이.. 착하고 다정한데 ..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/18926930",
        "title": "썰 (+ 추가)",
        "author": "독",
        "date": "2025. 4. 8.",
        "is_adult": "True",
        views: 2300,
        price: 0,
        likes: 119,
        "category": "novel",
        "summary": "잡식공룡 님과 이야기하다가 나왔던 걸 짧게(?) 정리해 봤습니다. 가볍게 읽어주세요. 맥락 없음. 서사 없음. 글로 쓸 예정 없음. 연애 8년, 헤어진 지 3개월 막 별것도 아닌 ..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/17935911",
        "title": "42",
        "author": "독",
        "date": "2024. 11. 4.",
        "is_adult": "True",
        views: 2400,
        price: 0,
        likes: 118,
        "category": "novel",
        "summary": "텍스트 10,029 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@absolute-g/post/17857854",
        "title": "돌의 녹는점",
        "author": "게라",
        "date": "2024. 10. 20.",
        "is_adult": "False",
        views: 1300,
        price: 0,
        likes: 105,
        "category": "novel",
        "summary": "하아.... 이 한숨 소리는 골목길에서 남들이 피운 담배꽁초 위에 쭈그려 앉은 22세 송은석의 것이었다. 그의 얼굴을 한 번 자세히 보자. 잘생겼다. 세상 근심이라는 것이 생기..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/18313267",
        "title": "42",
        "author": "독",
        "date": "2025. 1. 1.",
        "is_adult": "True",
        views: 2000,
        price: 0,
        likes: 102,
        "category": "novel",
        "summary": "텍스트 8,095 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@lovepilldonknow/post/20125547",
        "title": "선천적 로맨스는 범죄! 上",
        "author": "노도",
        "date": "2025. 8. 6.",
        "is_adult": "True",
        views: 2300,
        price: 0,
        likes: 93,
        "category": "novel",
        "summary": "영상 클릭 > 톱니 바퀴 > 아래로 스크롤 > 옵션 더보기 > 연속 재생 애니 좀 봤다, 뭐라고 하는지 어느 정도 들린다, 좋은 아침 좋은 점심 좋은 저녁을 야무지게 구분할 수 있..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/17986993",
        "title": "거짓 고백",
        "author": "독",
        "date": "2024. 11. 11.",
        "is_adult": "True",
        views: 1700,
        price: 0,
        likes: 84,
        "category": "novel",
        "summary": "텍스트 7,248 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@lovepilldonknow/post/20531736",
        "title": "선천적 로맨스는 범죄! 下",
        "author": "노도",
        "date": "2025. 9. 27.",
        "is_adult": "True",
        views: 1200,
        price: 0,
        likes: 82,
        "category": "novel",
        "summary": "영상 클릭 > 톱니 바퀴 클릭 > 스크롤 아래로 슬라이드 > 연속 재생 쌍자흡충에 대해 생각했다. 일반적으로 민물고기의 아가미에 붙어사는 기생충 말고. 이른 바, 영화 '사랑하는 ..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/19253907",
        "title": "경계",
        "author": "독",
        "date": "2025. 7. 17.",
        "is_adult": "False",
        views: 780,
        price: 0,
        likes: 81,
        "category": "novel",
        "summary": "마지막 열아홉의 충동은 지나쳤다. 대충 후드를 뒤집어쓴 채 찍은 셀카를 업로드하고 스무살이라는 거짓말 아닌 거짓말을 적는 동안 고민한 적이 없다면 그것 또한 거짓말이겠지만 채 5분..."
    },
    {
        "url": "https://www.postype.com/@stone69/post/20005985",
        "title": "돌른 석른 썰 백업2",
        "author": "ㅅㄸㅅㄸ",
        "date": "2025. 7. 24.",
        "is_adult": "True",
        views: 3000,
        price: 0,
        likes: 80,
        "category": "novel",
        "summary": "알오 세계관이라면? 에 대한 썰조각들 숑석은 우성알파x열성알파인데 중간에 이물질 오메가 낀 사이로 ㅂㄱㅅㄷ 오메가 집안이 ㅈㄴ 좋음 근데 진짜 보통 망나니가 아니라 다들 집안으로라..."
    },
    {
        "url": "https://www.postype.com/@underwaterss/post/20033157",
        "title": "はつこい (첫사랑)",
        "author": "수도꼭지",
        "date": "2025. 7. 30.",
        "is_adult": "True",
        views: 1700,
        price: 0,
        likes: 79,
        "category": "novel",
        "summary": "*숑석 라이프 오버 워터 https://posty.pe/skwg6nm 의 숕석 외전입니다. *수술장면 묘사가 있습니다. 한국에 와 처음으로 사회 생활을 시작한 쇼타로는 한국에 와서..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/19289809",
        "title": "해피엔드 上",
        "author": "독",
        "date": "2025. 5. 16.",
        "is_adult": "True",
        views: 873,
        price: 0,
        likes: 60,
        "category": "novel",
        "summary": "길고 긴 전쟁이었다. 태어날 때부터 누가 아군인지, 누가 적군인지 모르는 채로 반복되는 싸움에 쇼타로는 이미 지쳐있었다. 부모의 얼굴은 기억나지 않았다. 아마도 기억이 있는 나이가..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/21223225",
        "title": "낫 리얼",
        "author": "독",
        "date": "2026. 1. 11.",
        "is_adult": "True",
        views: 880,
        price: 0,
        likes: 56,
        "category": "novel",
        "summary": "* 약간의 날조와 망상 텍스트 8,772 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@00010v2/post/22547007",
        "title": "쓰레기 개조법",
        "author": "롵",
        "date": "2026. 6. 24.",
        "is_adult": "True",
        views: 591,
        price: 0,
        likes: 55,
        "category": "novel",
        "summary": "*적폐 캐해 주의 오사키 쇼타로가 오랜만에 본가에 다녀오는 길, ‘덜덜덜-’ 몸보다 큰 캐리어 끌며 도착한 곳이 본인 집이 아니라 여자 친구의 집인 것은 바로 어제 카톡으로 온 사..."
    },
    {
        "url": "https://www.postype.com/@sesesc/post/21288265",
        "title": "숕석",
        "author": "uc",
        "date": "2026. 1. 6.",
        "is_adult": "False",
        views: 365,
        price: 0,
        likes: 51,
        "category": "webtoon",
        "summary": "좀 쌓여서 옛날꺼까지 다 모아서 같이 백업합니둥"
    },
    {
        "url": "https://www.postype.com/@stone69/post/18247605",
        "title": "숕석에 대한 깊생고찰",
        "author": "ㅅㄸㅅㄸ",
        "date": "2024. 12. 18.",
        "is_adult": "True",
        views: 2300,
        price: 0,
        likes: 50,
        "category": "novel",
        "summary": "냉한 면모를 송한테 잘 보야주는 숕과 관심받고싶은 초딩처럼 숕한테 치대고 맴돌고 장난치고 놀리고 만지작거리는 송 (+) 발행하다가 추가하고싶어서 추가한 캐해, 근데 사실 이게 숕석..."
    },
    {
        "url": "https://www.postype.com/@japsikgr/post/17873181",
        "title": "충동의 말로",
        "author": "잡식몬스터",
        "date": "2024. 11. 16.",
        "is_adult": "False",
        views: 714,
        price: 0,
        likes: 50,
        "category": "novel",
        "summary": "평소와 다를 바 없는 하루였다. 7시에 알람 듣고 일어나, 겨우 준비 마치고 차에 타면 7시 45분. 하품 쩍쩍 해가며 운전해 주차까지 마치고 나면 8시 25분. 사무실 옆 24시..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/20923021",
        "title": "익숙한 타인 上",
        "author": "독",
        "date": "2026. 2. 6.",
        "is_adult": "False",
        views: 558,
        price: 0,
        likes: 47,
        "category": "novel",
        "summary": "텍스트 8,073 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/19480497",
        "title": "해피엔드 下",
        "author": "독",
        "date": "2025. 6. 1.",
        "is_adult": "True",
        views: 705,
        price: 0,
        likes: 47,
        "category": "novel",
        "summary": "생산번호 S319. 은석이 가장 처음 부여받은 이름이었다. 센티넬과 가이드의 등급을 세분화하면 셀 수 없이 많았지만, 크게는 S, A, B, C로 나뉘었다. 그 이하는 사실 능력이..."
    },
    {
        "url": "https://www.postype.com/@00010v2/post/22097713",
        "title": "레몬스퀴지 1",
        "author": "롵",
        "date": "2026. 4. 25.",
        "is_adult": "True",
        views: 695,
        price: 0,
        likes: 44,
        "category": "novel",
        "summary": "안녕하세요? 안녕하세요. 식사 하고 오셨어요? 근처에 만둣집 있길래, 먹고 왔습니다. 그럼 인터뷰 시작하겠습니다. 네. 혹시 인생에서 후회한 경험 있으신가요? 있죠. 언제인지 말씀..."
    },
    {
        "url": "https://www.postype.com/@edamame/post/18659333",
        "title": "Arab Tofu Theory 上",
        "author": "완두콩",
        "date": "2025. 3. 21.",
        "is_adult": "False",
        views: 807,
        price: 0,
        likes: 43,
        "category": "novel",
        "summary": "아랍두부이론 - 이목구비가 진한 사람은 본인과 정반대로 말랑말랑하게 생긴 사람에게 끌린다는 이론 Rise&Realize GYM, 줄여 부르길 알앤알짐. 이 곳 대표이자 트레이너인 ..."
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/21864824",
        "title": "익숙한 타인 下",
        "author": "독",
        "date": "2026. 4. 1.",
        "is_adult": "True",
        views: 409,
        price: 0,
        likes: 42,
        "category": "novel",
        "summary": "텍스트 7,793 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@sweetpoison/post/21588896",
        "title": "익숙한 타인 中",
        "author": "독",
        "date": "2026. 3. 11.",
        "is_adult": "True",
        views: 421,
        price: 0,
        likes: 42,
        "category": "novel",
        "summary": "* 제 기준 성인 글은 아니지만, 혹시 모르니... 텍스트 7,551 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@japsikgr/post/18687090",
        "title": "It's no secret!",
        "author": "잡식몬스터",
        "date": "2025. 3. 19.",
        "is_adult": "False",
        views: 437,
        price: 0,
        likes: 37,
        "category": "novel",
        "summary": "오랜만에 모이자는 연락을 받고 참석한 모임의 인원은 단촐했다. 마지막 동아리장 정성찬, 그 정성찬이 끼고 다니던 이찬영, 친구 따라 왔다가 혼자 남은 송은석과 이소희, 한국어 실력..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/18633647",
        "title": "코코로오도루 1",
        "author": "키브",
        "date": "2025. 3. 3.",
        "is_adult": "False",
        views: 383,
        price: 0,
        likes: 35,
        "category": "novel",
        "summary": "경영22 송은석은 춤을 좋아하지 않는다. 싫어한다기 보단 그냥 시키면 추고 안 시키면 안 췄다. 그래도 석 달에 한 번 꼴로 있는 공연에는 눈치껏 대충 참여했다. 형은 대체 여기 ..."
    },
    {
        "url": "https://www.postype.com/@seaneo/post/16197232",
        "title": "비틀린 삼각관계",
        "author": "에탄올",
        "date": "2024. 2. 24.",
        "is_adult": "True",
        views: 1700,
        price: 1700,
        likes: 34,
        "category": "novel",
        "summary": "삼각관계, 리얼물, 후회공 팬들과 라이즈 주변 관계자들은 은연중에 성찬과 쇼타로가 사귀는 사이일 거라고 짐작했다. 하지만 쇼타로와 교제하고 있는 것은 놀랍게도 은석이었는데... 가..."
    },
    {
        "url": "https://www.postype.com/@sudada/post/21079963",
        "title": "빠의순정 1",
        "author": "sudada",
        "date": "2025. 12. 21.",
        "is_adult": "False",
        views: 295,
        price: 0,
        likes: 27,
        "category": "novel",
        "summary": "소재주의 사람은 살기위해돈을번다. 맞다. 은석도 살기위해돈을벌엇다. 오후에는 마끄로나르도에서 레지 앤나 인간튀김기대행 앤나 햄버거만드는기계 겸업으로 일햇으며 열두시부터 네시까지는 ..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/19757056",
        "title": "테노히라 下",
        "author": "키브",
        "date": "2025. 6. 26.",
        "is_adult": "False",
        views: 328,
        price: 0,
        likes: 26,
        "category": "novel",
        "summary": "주혜가 고맙다고 전해달라네요. 그리고…. 다신 오지 말라고 합니다. 정말 미안해요. 아니요. 괜찮습니다. 사과를 전하는 중년의 부부에게 애써 씁쓸한 웃음을 지어 보였다. 병원을 나..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/19728398",
        "title": "테노히라 上",
        "author": "키브",
        "date": "2025. 6. 23.",
        "is_adult": "False",
        views: 385,
        price: 0,
        likes: 26,
        "category": "novel",
        "summary": "은석~ 또. 또 저 말투 저거. 송은석~ 존나 끈질기네. 나는 은석 조아. 어쩌라고? 은석이도 나 좋지? 통화 종료 버튼 위에 올린 손가락이 달달 떨렸다. 나 안 좋아? 스피커폰을..."
    },
    {
        "url": "https://www.postype.com/@00010v2/post/21388632",
        "title": "신인류는 구시대적 [사랑]따위 하지 않는다",
        "author": "롵",
        "date": "2026. 1. 18.",
        "is_adult": "False",
        views: 357,
        price: 0,
        likes: 24,
        "category": "novel",
        "summary": "20세기가 막을 내렸다. 그다지도 말 많고 탈 많았으나 누구에게나 노이즈 잔뜩 낀 기억을 남기고 20세기는 떠났다. 지구가 멸망할 거라느니, 외계인이 들이닥친다느니. 지금 생각하면..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/19607111",
        "title": "코코로오도루 4",
        "author": "키브",
        "date": "2025. 6. 21.",
        "is_adult": "False",
        views: 173,
        price: 0,
        likes: 24,
        "category": "novel",
        "summary": "'공연 D-3' 박원빈이 빨간 글씨가 적힌 종이를 동아리방 문에 앞뒤로 꼼꼼히 붙였다. 너는 시험보다 공연이 더 중요하지? 송은석이 팔짱을 끼고 비아냥거렸다. 그러자 박원빈이 지지..."
    },
    {
        "url": "https://www.postype.com/@edamame/post/19201071",
        "title": "Arab Tofu Theory 中",
        "author": "완두콩",
        "date": "2025. 8. 10.",
        "is_adult": "False",
        views: 366,
        price: 0,
        likes: 23,
        "category": "novel",
        "summary": "아랍두부이론 - 이목구비가 진한 사람은 본인과 정반대로 말랑말랑하게 생긴 사람에게 끌린다는 이론. “은석이랑 원빈이는 무슨 무슨 나라 왕자님들 같어.” “그니까. 나 이렇게 잘생긴..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/18964540",
        "title": "코코로오도루 2",
        "author": "키브",
        "date": "2025. 5. 22.",
        "is_adult": "False",
        views: 229,
        price: 0,
        likes: 22,
        "category": "novel",
        "summary": "지난 며칠간 박원빈이 지켜본 쇼타로는 하나도 바뀐 게 없었다. 되려 그게 더 이상했다. 송은석한테든 본인한테든 전과 똑같이 대하는 게 말이 안 됐다. 뒤에서 좋아하네 마네 하는 걸..."
    },
    {
        "url": "https://www.postype.com/@moldingwhat/post/17440322",
        "title": "숕석/숕돌 커미션",
        "author": "미미",
        "date": "2024. 8. 21.",
        "is_adult": "False",
        views: 720,
        price: 0,
        likes: 22,
        "category": "novel",
        "summary": "<삼> to soup by me!me 은석은 세번째 심부름을 받았다. 마침 은석의 이름은 ‘三(さん)’이다. 출발지는 〒123-4567, 도쿄도, xx구, 00쵸. 주택단지 입구에..."
    },
    {
        "url": "https://www.postype.com/@oooopn/post/20228397",
        "title": "썰백업 2",
        "author": "dam",
        "date": "2025. 8. 29.",
        "is_adult": "True",
        views: 1100,
        price: 800,
        likes: 21,
        "category": "novel",
        "summary": "빻앗어요 /. 숑석 고전물 2 /. 숑석 디엣 /. 넨석 디엣 /. 숕석 디엣 /. 약 톤석 텍스트 6,630 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@shotaroleft/post/20165872",
        "title": "미묘한 삼각관계",
        "author": "ㅈㅌ",
        "date": "2025. 8. 10.",
        "is_adult": "False",
        views: 403,
        price: 0,
        likes: 20,
        "category": "novel",
        "summary": "야 은석아! 쟤 누군지 알아? 아까부터 너 쳐다보던데. 송은석은 반 친구의 말에 뒤를 돌아보았다. 키 크고 하얀 남자애가 멍한 듯 따가운 시선으로 저를 바라보고 있었다. 송은석..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/19821945",
        "title": "코코로오도루 5 (完)",
        "author": "키브",
        "date": "2025. 7. 31.",
        "is_adult": "False",
        views: 194,
        price: 0,
        likes: 20,
        "category": "novel",
        "summary": "긴급. 비상. 존나 비상. 그냥빨리나와 송은석에게 온 문자였다. 그러고 보니 공연 끝나고 도망치듯이 없어졌었지…. 박원빈은 답장을 보내려다가 잠깐 망설였다. 나도 눈치라는 게 있거..."
    },
    {
        "url": "https://www.postype.com/@kivparallel/post/19529391",
        "title": "코코로오도루 3",
        "author": "키브",
        "date": "2025. 5. 28.",
        "is_adult": "False",
        views: 233,
        price: 0,
        likes: 20,
        "category": "novel",
        "summary": "송은석과 '쇼타로 질투 유발 작전'이라는 유치한 연극을 시작한 지 고작 3시간 째, 박원빈은 새삼 깨달았다. 본인이 연기에 젬병이라는 것을. 동아리방에서 쇼타로를 만나 갑자기 밥을..."
    },
    {
        "url": "https://www.postype.com/@sudada/post/21302214",
        "title": "빠의순정2",
        "author": "sudada",
        "date": "2026. 4. 7.",
        "is_adult": "False",
        views: 104,
        price: 0,
        likes: 19,
        "category": "novel",
        "summary": "은석은 매사 여유로웠다. 아니. 남들이 그를 그렇게 여겼다. 그 이유의 10에 8할은 감정의 진폭이 크지 않고 서두르지 않고 길가다 뒤통수를 처맞아도 엥? 아. 예. 하고 지나갈 ..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18775709",
        "title": "돌 쟁탈전 上",
        "author": "얼음땡",
        "date": "2025. 5. 31.",
        "is_adult": "False",
        views: 833,
        price: 0,
        likes: 17,
        "category": "novel",
        "summary": "본 이야기의 내용은 실제와 무관합니다 캐붕 주의 참고 은석 <쇼타로> 《성찬》 - 원빈 {소희} [앤톤] @멤버 전체 송은석, 내 나이 24살. 지금 내 인생 최대의 시련이 왔..."
    },
    {
        "url": "https://www.postype.com/@showertowel/post/18098577",
        "title": "우리가 헤어져야만 하는 이유",
        "author": "샴푸",
        "date": "2025. 7. 25.",
        "is_adult": "False",
        views: 340,
        price: 0,
        likes: 17,
        "category": "novel",
        "summary": "둘이 처음 만난건 12월 추운 겨울이었다. 은석은 집에서 주로 생활하고 추운 날 밖에 나가는건 질색이었지만 여자친구에게 차인 친구를 위로해주러 밖에 나왔다. 은석은 친구와 만나기로..."
    },
    {
        "url": "https://www.postype.com/@oooopn/post/20416590",
        "title": "비계썰백업 4",
        "author": "dam",
        "date": "2025. 9. 14.",
        "is_adult": "True",
        views: 1100,
        price: 900,
        likes: 15,
        "category": "novel",
        "summary": "빻앗으요 키워드 주의! /. 후궁숑황제석 (ㅇㅈㅍ) /. 숕주돌냥(ㅅㅌ) /. 톤석 야외플 (ㅂㅅ) 텍스트 7,043 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@kbg05024/post/21879602",
        "title": "아부라소바와 은석에 대한 기록?",
        "author": "배부루",
        "date": "2026. 3. 19.",
        "is_adult": "False",
        views: 185,
        price: 0,
        likes: 12,
        "category": "novel",
        "summary": "요즘 은석이가 이상하다. 아니? 평소와 같다고 해야 하나.. 냠- 우물우물- 진지한 얼굴로 은석을 바라보자 우물거리는 입을 열고 왜. 뭐 본인도 찔리는지 툭툭거리는 말투다. ..."
    },
    {
        "url": "https://www.postype.com/@shotaroleft/post/20526054",
        "title": "제가 보스메이커가 되겠습니다",
        "author": "ㅈㅌ",
        "date": "2025. 10. 18.",
        "is_adult": "False",
        views: 136,
        price: 0,
        likes: 12,
        "category": "novel",
        "summary": "보스가 죽었다. 그리고 그에는 은석의 공이 컸다. 은석이 꾸민 일이었으니까. 은석은 남의 미래는 귀신처럼 점치면서 자신의 미래는 한 치 앞도 몰랐다. 그러므로 이런 상황이 그에게 ..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/19022240",
        "title": "조각을 모아드립니다",
        "author": "얼음땡",
        "date": "2025. 6. 8.",
        "is_adult": "False",
        views: 634,
        price: 0,
        likes: 6,
        "category": "novel",
        "summary": "(2025년 3월 24일 추가) 텍스트 4,816 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18822683",
        "title": "돌 쟁탈전 中",
        "author": "얼음땡",
        "date": "2025. 5. 31.",
        "is_adult": "False",
        views: 333,
        price: 0,
        likes: 6,
        "category": "novel",
        "summary": "죽음, 자살 소재 주의 ??? : 은석이 형... 일어나 누구지? 익숙한 목소리다 ??? : 형, 일어나 내가 잊고 살아가던 소중한 사람, 동생의 목소리다 왜? 이제 왔어? 내가..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/20065265",
        "title": "썰 대방출",
        "author": "얼음땡",
        "date": "2025. 7. 30.",
        "is_adult": "False",
        views: 659,
        price: 0,
        likes: 4,
        "category": "novel",
        "summary": "이걸 이어서 쓸지 안 쓸지 몰라서 올려봅니다 반응 좋은 글은 더 써올게요 그럼 재밌게 읽어주세요 텍스트 3,040 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18913976",
        "title": "돌 쟁탈전…? 下",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 355,
        price: 0,
        likes: 4,
        "category": "novel",
        "summary": "텍스트 4,409 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18862448",
        "title": "돌 쟁탈전…? 上",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 418,
        price: 0,
        likes: 3,
        "category": "novel",
        "summary": "텍스트 4,657 자 공백 제외"
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18845427",
        "title": "돌 쟁탈전 下",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 250,
        price: 0,
        likes: 3,
        "category": "novel",
        "summary": "편지도 다 썼겠다. 이제 자야지... 내일 일찍 나가야 하니깐. 행복할 기회를 안 주네. 내 몸이 밉다. 이젠 행복해질 수 있을 거 같았는데 또... 지난번엔 동생이 죽더니 이번엔..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18833723",
        "title": "돌 쟁탈전 中中",
        "author": "얼음땡",
        "date": "2025. 5. 31.",
        "is_adult": "False",
        views: 291,
        price: 0,
        likes: 2,
        "category": "novel",
        "summary": "<자~ 은석이의 퇴원을 축하하며!> 퇴원 하는 거까지 축하받다니;; 희한하네 <오늘은 우리 술 못 마신다. 은석이가 술 금지 당했거든ㅠ> 진짜? <엉, 의사 선생님이 한 주 동..."
    },
    {
        "url": "https://www.postype.com/@frozen-everything/post/18891223",
        "title": "돌 쟁탈전…? 中",
        "author": "얼음땡",
        "date": "2025. 6. 2.",
        "is_adult": "False",
        views: 223,
        price: 0,
        likes: 1,
        "category": "novel",
        "summary": "텍스트 4,562 자 공백 제외"
    }
]